FROM golang
MAINTAINER Jan Broer <jan@festplatte.eu.org>

RUN apt-get install ca-certificates
RUN make build && make image

ADD build/rancher-letsencrypt-linux-amd64 /usr/bin/rancher-letsencrypt

RUN chmod +x /usr/bin/rancher-letsencrypt

ENTRYPOINT ["/usr/bin/rancher-letsencrypt", "-debug"]
