FROM golang
MAINTAINER Jan Broer <jan@festplatte.eu.org>

COPY . /root/code
WORKDIR /root/code

RUN make deps && make build

ADD build/rancher-letsencrypt-linux-amd64 /usr/bin/rancher-letsencrypt

RUN chmod +x /usr/bin/rancher-letsencrypt

ENTRYPOINT ["/usr/bin/rancher-letsencrypt", "-debug"]
